### ISSUE TITLE
sharing doesn't appear

### ISSUE THREAD

**Issue by itdev123** [linweigao/react-native-app-share-extension#1]
Hi, LinWeiGao
Thanks for your example.
I have some questions about sharing on iOS
I followed your examples, but it's not working correctly on my side.
Could you check my source code?
[MobileSharing.zip](https://github.com/linweigao/react-native-app-share-extension/files/2664251/MobileSharing.zip)
Thanks

**Comment by itdev123** [comment]
I pushed to github.
https://github.com/itdev123/React-Native-Share-Extension-for-iOS
On emulator, it works well. But on real device, sharing screen doesn't appear.

**Comment by linweigao** [comment]
Could you give more details about in which step sharing screen doesn't appear?
Maybe iOS version, device type will be helpful.

**Comment by itdev123** [comment]
Thanks for your reply.
When clicking MobileSharingEx button in camera or web browser, nothing shows.
I tested on a few iPhones, but the same.
I pushed the source code.
It works on your phone?
